[package]
name = "complete-blockchain"
version = "0.1.0"
edition = "2021"

[dependencies]
sha2 = "0.10"
chrono = { version = "0.4", features = ["serde"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
thiserror = "1.0"